micronaut:
  application:
    name: strava-oauth
  http:
    services:
      strava:
        url: "https://www.strava.com/api/v3/"
  security:
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:provideYourOwn}"'
    oauth2:
      clients:
        strava:
          client-id: '${OAUTH_CLIENT_ID:providerYourOwn}'
          client-secret: '${OAUTH_CLIENT_SECRET:provideYourOwn}'
          scopes:
            - activity:read_all,profile:write,activity:write
          authorization:
            url: https://www.strava.com/oauth/authorize
          token:
            url: https://www.strava.com/api/v3/oauth/token
            auth-method: CLIENT_SECRET_POST
    endpoints:
      logout:
        get-allowed: true